<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \App\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'assets', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'hideouts', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'missions'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'agents', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'targets', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'assets', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'hideouts', '' . "\0" . 'App\\Entity\\Country' . "\0" . 'missions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality(string $nationality): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgents', []);

        return parent::getAgents();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgent(\App\Entity\Agent $agent): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgent', [$agent]);

        return parent::addAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgent(\App\Entity\Agent $agent): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgent', [$agent]);

        return parent::removeAgent($agent);
    }

    /**
     * {@inheritDoc}
     */
    public function getTargets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTargets', []);

        return parent::getTargets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarget(\App\Entity\Target $target): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarget', [$target]);

        return parent::addTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarget(\App\Entity\Target $target): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarget', [$target]);

        return parent::removeTarget($target);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssets', []);

        return parent::getAssets();
    }

    /**
     * {@inheritDoc}
     */
    public function addAsset(\App\Entity\Asset $asset): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAsset', [$asset]);

        return parent::addAsset($asset);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAsset(\App\Entity\Asset $asset): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAsset', [$asset]);

        return parent::removeAsset($asset);
    }

    /**
     * {@inheritDoc}
     */
    public function getHideouts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHideouts', []);

        return parent::getHideouts();
    }

    /**
     * {@inheritDoc}
     */
    public function addHideout(\App\Entity\Hideout $hideout): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHideout', [$hideout]);

        return parent::addHideout($hideout);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHideout(\App\Entity\Hideout $hideout): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHideout', [$hideout]);

        return parent::removeHideout($hideout);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissions', []);

        return parent::getMissions();
    }

    /**
     * {@inheritDoc}
     */
    public function addMission(\App\Entity\Mission $mission): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMission', [$mission]);

        return parent::addMission($mission);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMission(\App\Entity\Mission $mission): \App\Entity\Country
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMission', [$mission]);

        return parent::removeMission($mission);
    }

}
