<?php

namespace Container1DD5Wpy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1WMJv05Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1WMJv05' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1WMJv05'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'missionRepository' => ['privates', 'App\\Repository\\MissionRepository', 'getMissionRepositoryService', true],
        ], [
            'missionRepository' => 'App\\Repository\\MissionRepository',
        ]);
    }
}
