<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3MIElxE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3MIElxE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3MIElxE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3MIElxE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3MIElxE\App_KernelDevDebugContainer([
    'container.build_hash' => '3MIElxE',
    'container.build_id' => '9dc0fbaa',
    'container.build_time' => 1630670659,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3MIElxE');
