<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRceD6h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRceD6h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRceD6h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRceD6h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRceD6h\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRceD6h',
    'container.build_id' => '40a16f54',
    'container.build_time' => 1631293781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRceD6h');
