<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB6eIpay\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB6eIpay/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB6eIpay.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB6eIpay\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB6eIpay\App_KernelDevDebugContainer([
    'container.build_hash' => 'B6eIpay',
    'container.build_id' => 'e75d5cf0',
    'container.build_time' => 1631797643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB6eIpay');
